app: appDemo
stage: dev

component: nuxtjs@dev
name: nuxtjsDemo

inputs:
  src:
    hook: npm run build
    dist: ./
    exclude:
      - .env
  region: ap-guangzhou
  functionConf:
    name: ${name}
    runtime: Nodejs10.15
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
  staticConf:
    cosConf:
      replace: true
      bucket: nuxtjs-demo
